# Header
menu:
  home: https://gregjs.com
  blog: https://gregjs.com/blog
  about: https://gregjs.com/about
  projects: https://gregjs.com/projects
  archives: https://gregjs.com/archives
  rss: https://gregjs.com/atom.xml
rss: https://gregjs.com/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-69518818-1
favicon: /images/favicon.png
highlight_theme: "hybrid"
