# Header
menu:
  home: http://www.gregjs.com
  blog: http://www.gregjs.com/blog
  about: http://blog.gregjs.com/about
  projects: http://blog.gregjs.com/projects
  archives: http://blog.gregjs.com/archives
  rss: http://blog.gregjs.com/atom.xml
rss: http://blog.gregjs.com/atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics: UA-69518818-1
favicon: /favicon.png
highlight_theme: "hybrid"
