# Header
menu:
  blog: https://gregjs.com/blog
  about: https://gregjs.com/about
  projects: https://gregjs.com/projects
  archives: https://gregjs.com/archives
  rss: https://gregjs.com/atom.xml
rss: https://gregjs.com/atom.xml

# Content
excerpt_link: Read More
fancybox: false # TODO: reimplement with preact
webpack: true

# Miscellaneous
google_analytics: UA-69518818-1
favicon: /images/favicon.png
highlight_theme: "hybrid"

# Sharing (true/false)
share: true
share_twitter: true
share_facebook: true
share_googleplus: true
share_email: true
share_reddit: true
share_linkedin: true
